### ISSUE TITLE
Implement button to delete a fridge

### ISSUE THREAD

**Issue by mtuntang** [What-The-Fridge/What-The-Fridge#12]
When clicking this button, must delete all items owned by that fridge and then delete the fridge it self.
This happens:
![image](https://user-images.githubusercontent.com/51338218/149478946-a7c4639d-f826-4fc4-badb-597584ffd2d2.png)

**Comment by mtuntang** [comment]
Partially done, can delete empty fridges. Need to implement a new mutation to clear all fridgeItems in a fridge

**Comment by hungnguyen3** [comment]
this was implemented
