### ISSUE TITLE
Implement on successful fridge creation, fridge item creation ->show indication for success and then exit fridge creation page

### ISSUE THREAD

**Issue by mtuntang** [What-The-Fridge/What-The-Fridge#8]
Quality of life improvement to prevent users from spamming multiple fridge creations
![image](https://user-images.githubusercontent.com/51338218/149271773-0adde59a-4f9f-4f52-a895-09ffa3b90997.png)
![image](https://user-images.githubusercontent.com/51338218/149271952-2ebe42a4-11e2-4eab-b392-e2b052dd81cb.png)
![image](https://user-images.githubusercontent.com/51338218/149275735-1f39c5b7-fd54-4d03-8857-3e0d49c35618.png)

**Comment by hungnguyen3** [comment]
done!
